name: docs

on:
  workflow_run:
    workflows: ["test"]
    branches: [main]
    types:
      - completed

jobs:
  docs:
    runs-on: ubuntu-20.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - id: deployment
        uses: sphinx-notes/pages@v3
        with:
          pyproject_extras: "sphinx-click recommonmark"
