name: docs
on: [push, pull_request, workflow_dispatch]
permissions:
  contents: write
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install dependencies
        run: |
          pip install sphinx sphinx-click recommonmark
      - name: build docs and commit
        run: |
          git clone https://github.com/your_git/repository.git --branch gh-pages --single-branch gh-pages
          cd docs
          make html
          cd _build/html
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update documentation" -a || true
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          directory: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
